version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - MARIADB_PASSWORD=my_passwd
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:1.7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_DATABASE_PASSWORD=my_passwd
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_FIRST_NAME=Toto
      - PRESTASHOP_LAST_NAME=FAMILLE
      - PRESTASHOP_PASSWORD=bitnami1
      - PRESTASHOP_EMAIL=user@example.com
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_COUNTRY=fr
      - PRESTASHOP_LANGUAGE=fr
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_PROTOCOL=tls
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASSWORD=your_password
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb
  phpmyadmin:
    image: 'bitnami/phpmyadmin:4'
    ports:
      - '8080:80'
      - '8443:443'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
  phpmyadmin_data:
    driver: local
